### ISSUE TITLE
Failed to find domain in string.

### ISSUE THREAD

**Issue by mccluret** [fhightower/ioc-finder#104]
Note: messed with the URLs/domain letters to ensure the string is not malicious.

To recreate simply run find_iocs and notice the missing domain. It works when you pass the unquoted text, however, this appends the unquoted URL which is technically incorrect and bad for research.

My workaround is currently to import the parse_domains function and pass that the unquoted text. 

https://asf.goole.com/mail?url=http%3A%2F%2Ffreasdfuewriter.com%2Fcs%2Fimage%2FCommerciaE.jpg&t=1575955624&ymreqid=733bc9eb-e8f-34cb-1cb5-120010019e00&sig=x2Pa2oOYxanG52s4vyCEFg--~C<http://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip>

Expected to return freasdfuewriter.com in domains, however, it is missing.

**Comment by fhightower** [comment]
Hi @mccluret, thanks for sharing this! If I understand your comment, there are two bugs here:

# First Bug

When calling the `find_iocs` function with:

```
https://asf.goole.com/mail?url=http%3A%2F%2Ffreasdfuewriter.com%2Fcs%2Fimage%2FCommerciaE.jpg&t=1575955624&ymreqid=733bc9eb-e8f-34cb-1cb5-120010019e00&sig=x2Pa2oOYxanG52s4vyCEFg--~Chttp://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip
```
  
we expect it to find this URL

```
https://asf.goole.com/mail?url=http%3A%2F%2Ffreasdfuewriter.com%2Fcs%2Fimage%2FCommerciaE.jpg&t=1575955624&ymreqid=733bc9eb-e8f-34cb-1cb5-120010019e00&sig=x2Pa2oOYxanG52s4vyCEFg--~Chttp://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip
```

But instead it finds this one:

```
https://asf.goole.com/mail?url=http://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip
```

# Second Bug

When calling `find_iocs` (or `parse_domains`) on the string, it should find `freasdfuewriter.com`, but it does not.

---

Is that a correct understanding of the problems?

**Comment by fhightower** [comment]
I'm working on this issue. At the moment, I believe part of the problem is in the [ioc-fanger](https://github.com/ioc-fang/ioc-fanger).

When running:

```
import ioc_fanger

s = 'https://asf.goole.com/mail?url=http%3A%2F%2Ffreasdfuewriter.com%2Fcs%2Fimage%2FCommerciaE.jpg&t=1575955624&ymreqid=733bc9eb-e8f-34cb-1cb5-120010019e00&sig=x2Pa2oOYxanG52s4vyCEFg--~Chttp://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip'
ioc_fanger.fang(s)
```

We get:

```
https://asf.goole.com/mail?url=http://uniddloos.zddfdd.org/CBA0019_file_00002_pdf.zip
```

**Comment by fhightower** [comment]
I've updated ioc-finder in version `v5.0.3` to fix this issue 🎉 .

Specifically, I've updated ioc-finder to properly percent decode URLs so that domain names and other observables can be parsed from them.

Thanks for reporting this @mccluret and please let me know if you have any questions or if this update does not resolve your issue.
