### ISSUE TITLE
Speed up parsing

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#196]
Are there ways we can speed up parsing? Perhaps restructuring grammars, using a different grammar library, or using more regexes in our grammars?

**Comment by FANGOD** [comment]
Yes, I need it too, the parsing speed is very slow, about 20 minutes for a 3M file, and I have some 50M files...

**Comment by fhightower** [comment]
Using [scalene](https://github.com/plasma-umass/scalene), I was able to identify which points are the slowest. You can see the worst offenders here:

![Screen Shot 2022-06-22 at 08 52 11](https://user-images.githubusercontent.com/3599813/175033591-aa3a8c0e-673d-4188-a0cc-55663bde37ec.png)

The `scheme_less_url` grammar and `enterprise_attack_techniques_grammar` are the worst offenders and will be addressed first.

**Comment by fhightower** [comment]
I'm tracking the work to speed this library up in [this milestone](https://github.com/fhightower/ioc-finder/milestone/2).

**Comment by fhightower** [comment]
Update on this: I just released version `7.2.1` which fixes a bug I introduced (sorry!) that caused significant unnecessary slowness. While I continue to work on speeding up the grammar, please update to `7.2.1`!

**Comment by frikky** [comment]
> Update on this: I just released version `7.2.1` which fixes a bug I introduced (sorry!) that caused significant unnecessary slowness. While I continue to work on speeding up the grammar, please update to `7.2.1`!

Thanks! Just updated the relevant systems's tests to use 7.2.1 to make sure it's not breaking anything else :)

**Comment by fhightower** [comment]
The changes made in #250 will SIGNIFICANTLY improve performance (conservatively ≈50% speed reduction).

**Comment by fhightower** [comment]
Version `7.2.2` was [released](https://github.com/fhightower/ioc-finder/blob/main/CHANGELOG.md#722---20220708) which reduces mean run-time by [≈70%](https://github.com/fhightower/ioc-finder/pull/253/files#diff-8e67b346e4b32f0cd637dbd271c16ab649c05fdf6aa7fe443cc85c0d8ca6ad07R149)!

I'm closing this ticket out speed has drastically improved and we have ticketed additional work in [this milestone](https://github.com/fhightower/ioc-finder/milestone/2).
