### ISSUE TITLE
Consider parsing malware names

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#22]
We could use something like https://github.com/fhightower/malware_name_mapping to parse malware names from text.

**Comment by deadbits** [comment]
This could also be a good source for malware family names: https://malpedia.caad.fkie.fraunhofer.de/families

**Comment by fhightower** [comment]
That's a great resource, thanks @deadbits!

**Comment by fhightower** [comment]
I've implemented this in the most recent version. Example usage:

```python
s = 'Bublik Emotet Esfury Gootkit'
iocs = find_iocs(s)
malware_names = iocs['malware_names']
print(malware_names) # ['Esfury', 'Gootkit', 'Bublik', 'Emotet']
```
