### ISSUE TITLE
Registry key paths that contain whitespaces are truncated

### ISSUE THREAD

**Issue by Javiery3889** [fhightower/ioc-finder#46]
Windows registry keys paths are truncated from the whitespace character onwards, as such full path is not displayed in the output. Below is how to replicate the error on Python 3.6.7.

```python
from ioc_finder import find_iocs
text = "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\ConsoleIME"
iocs = find_iocs(text)
print(iocs['registry_key_paths'])
# output: ['HKLM\\SOFTWARE\\Microsoft\\Windows']
```
The error seems to occur because pyparsing grammars ignores whitespace by default, specifically in line 167 of ioc_grammers.py as shown below.
```python
registry_key_subpath = OneOrMore(Word('\\') + Word(alphanums))
```
One quick workaround that I discovered when working with whitespaces and pyparsing is to use the `White()` class in pyparsing as shown below.
```python
registry_key_subpath = OneOrMore(Word('\\') +  Combine(OneOrMore(Word(alphanums)| White(' ',max=1) + ~White())))
``` 

References:
- https://stackoverflow.com/questions/26600333/pyparsing-whitespace-match-issues
- https://pythonhosted.org/pyparsing/pyparsing.White-class.html

**Comment by fhightower** [comment]
Thanks for reporting this @Javiery3889 ! And thank you for looking into the problem; that is really helpful (and most people don't do that)! I'll take a look and will hopefully have a fix soon.

**Comment by fhightower** [comment]
I've pushed an update to fix this issue. Thanks again for reporting! With the new implementation, there is one caveat (which I've noted in the [readme](https://github.com/fhightower/ioc-finder#known-limitations)):

A registry key path with a space in the final section (the part after the final `\`) will not be taken as part of the registry key. For example:

`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\ConsoleIME` will be parsed as `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\ConsoleIME`

and

`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\ConsoleIME foo...` will be parsed as `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\ConsoleIME` (notice that everything after the space in the last section is removed)

**Comment by Javiery3889** [comment]
Hi @fhightower just discovered another bug regarding registry keys with multiple whitespaces, the path gets truncated as well shown below on Python 3.6.7.
```python
from ioc_finder import find_iocs
text = "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe"
iocs = find_iocs(text)
print(iocs['registry_key_paths'])
# output: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image'
```
However, I am unsure about the workaround this time, any advice? Thanks.

**Comment by fhightower** [comment]
Good catch. I'll take a look at that.

**Comment by fhightower** [comment]
Thanks for finding and reporting this @Javiery3889 ! I believe I have fixed the problem, but let me know if you find other edge-cases.
