### ISSUE TITLE
Avoid multiprocessing TimeoutError

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#62]
When trying to parse indicators from https://www.us-cert.gov/ncas/alerts/TA18-074A, I get the following error:

`python3.6/multiprocessing/pool.py:640: TimeoutError`

I want to make sure this does not happen or at least that it is unlikely to happen. I would like to address this as part of #56 and/or #60 .

**Comment by wesinator** [comment]
that is different than the issue that spurred #56, #60 btw

`AssertionError: daemonic processes are not allowed to have children`

**Comment by fhightower** [comment]
This is fixed with #65 . Using concurrent.futures removes the need for a timeout.
