### ISSUE TITLE
Malware names - regex not matching ?

### ISSUE THREAD

**Issue by wesinator** [fhightower/ioc-finder#64]
```python
import ioc_finder
ioc_finder.find_iocs("CRASHOVERRIDE crashoverride")
```
`crashoverride` does not match ?
`'malware_names': ['CRASH']`

haven't tested with c38a5c0 (#61)

**Comment by fhightower** [comment]
#61 fixed the problem (thanks for the PR!). Let me know if you run into any other problems.
