### ISSUE TITLE
Keyword regexes that are clearly in malware list are missing from list data output ?

### ISSUE THREAD

**Issue by wesinator** [fhightower/ioc-finder#67]
This is really confounding me:

python3.6 Ubuntu 18.04 
```python
import ioc_finder.data_lists

for i in ioc_finder.data_lists.malpedia_malware_name_regexes:
    if "dapato" in i.lower():
        print(i)
```

The list output doesn't include https://github.com/fhightower/ioc-finder/blob/3e2fa119498a0fb04e9a3b6d8c7d26e323251238/ioc_finder/data_lists.py#L2485 

tested both in package and standalone data_lists

I don't see any linter errors, but obviously something isn't right.
I suspected a missing comma, but if that were the case the string should still appear concatenated.

wonder if this is what happened in #64

**Comment by fhightower** [comment]
Thanks for reporting this @wesinator ! The problem was that I did not release this package to pypi until today, so `dapato` was not the in the list. Sorry about the delay in releasing to pypi (I'll update it more quickly in the future).
