### ISSUE TITLE
Drop support for malware names entirely

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#68]
I don't want to keep a list of malware names in this app. I'd like to keep/maintain them elsewhere.

**Comment by wesinator** [comment]
I've started a json structured data generated from the ioc finder lists https://github.com/wesinator/malware-fieldguide/blob/master/malware.json 

The aim of this was to provide an agnostic format reference with additional metadata about a malware name, but it still has the name/regex so you could pull names from there.

**Comment by fhightower** [comment]
I think I'm going to remove support for malware names entirely. Matching/finding malware names is a complex problem and should be solved elsewhere. I don't want to maintain a list of malware names (or any non-standardized content) and don't want to request/cache someone else's list.
