### ISSUE TITLE
Licensing issue (commercial vs non-commercial)

### ISSUE THREAD

**Issue by wagner-certat** [fhightower/ioc-finder#79]
The data seems to use data from Malpedia:
https://github.com/fhightower/ioc-finder/blob/d102d92f132105c2a30faeffe9d441e41bff2e8b/ioc_finder/data_lists.py#L2384
(btw I guess that the regex'ed data is copied from https://github.com/certtools/malware_name_mapping/blob/master/malpedia.csv)
But Malpedia data's license is CC BY-NC-SA 3.0 see https://malpedia.caad.fkie.fraunhofer.de/usage/tos
The license defined in the repository here is the [MIT-License](https://github.com/fhightower/ioc-finder/blob/d102d92f132105c2a30faeffe9d441e41bff2e8b/LICENSE)
They are not compatible at least in terms of commercial use.
I also don't see Malpedia honored anywhere.

cc @danielplohmann

**Comment by fhightower** [comment]
@wagner-certat : Thanks for pointing this out. I'll remove the data from malpedia.

I'm going to drop support for parsing malware names anyway (see https://github.com/fhightower/ioc-finder/issues/68) as it should really be done elsewhere.

**Comment by wagner-certat** [comment]
I think it's totally fine to (optionally) pull in the names (on demand) from an external source and point out the divergent license. That's how I do it here: https://github.com/certtools/intelmq/tree/develop/contrib/malware_name_mapping#malpedia-rules

**Comment by fhightower** [comment]
Thanks for the input! I'm going to remove parsing for malware names, but that's a really helpful example. Thanks for sharing it.

**Comment by wesinator** [comment]
@wagner-certat thanks for pointing this out, does this mean the Malpedia data can't be used in any project with a commercial use open source license ?

I mirrored the malware data from ioc-finder to https://github.com/wesinator/malware-fieldguide
