### ISSUE TITLE
Add Monero wallet

### ISSUE THREAD

**Issue by Maijin** [fhightower/ioc-finder#94]
Hi!

Just noticed ioc-finder haven't been able to scrape the monero wallet from the TENCENT report https://s.tencent.com/research/report/1105.html

**Comment by fhightower** [comment]
Hey @Maijin ! Thanks for reporting this. I've added support for monero wallets (shoutout to https://github.com/k4m4/monero-regex/blob/master/index.js for the regex) in the newest version of this package (v4.0.2 - on pypi now).
