### ISSUE TITLE
Not able to download file as response. 

### ISSUE THREAD

**Issue by Sammy94** [fhightower/ioc-finder#95]

**Comment by fhightower** [comment]
Hi @Sammy94 ! I'm sorry, but I don't understand the problem. Can you post a code snippet and describe what you are trying to accomplish? Also, in your comment you mention "Shuffle"; I don't know what Shuffle is.

**Comment by fhightower** [comment]
Hey @Sammy94, I'm going to close this issue for now. If you do have any other questions or issues, please feel free to reopen this issue.
